apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: 'https://backstage.github.io/charts'
    chart: backstage
    targetRevision: 1.0.0
    helm:
      parameters:
        - name: postgresql.enabled
          value: "false" # Use internal SQLite for demo/POC
        - name: backstage.command[0]
          value: "node"
        - name: backstage.command[1]
          value: "packages/backend"
        - name: backstage.command[2]
          value: "--config"
        - name: backstage.command[3]
          value: "app-config.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
