apiVersion: v1
kind: Service
metadata:
  name: openbao
  namespace: security
  labels:
    app: openbao
spec:
  ports:
    - port: 8200
      targetPort: 8200
      name: http
    - port: 8201
      targetPort: 8201
      name: cluster
  clusterIP: None
  selector:
    app: openbao

