apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foundation-service-mesh

resources:
  # Linkerd CRDs (Generated locally)
  - linkerd-crds.yaml
  # Linkerd Control Plane (Generated locally)
  - linkerd-control-plane.yaml
